general {
    # Команда, которая должна сработать при сигнале "before sleep" от системы
    before_sleep_cmd = noctalia-shell ipc call lockScreen lock
    
    # Команда для отключения экрана (опционально, для экономии энергии)
    # after_sleep_cmd = hyprctl dispatch dpms on
}

# Дополнительно: блокировка по таймеру простоя (idle)
# listener {
#     timeout = 10
#     on-timeout = noctalia-shell ipc call lockScreen lock
# }
