# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    loader = {
      grub = {
        enable = true;
        efiSupport = true;
        devices = [ "nodev" ];
        milk-theme.enable = true;
      };
      efi = {
        canTouchEfiVariables = true;
        efiSysMountPoint = "/boot/efi";
      };
    };
    initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "usb_storage"
      "usbhid"
      "sd_mod"
      "rtsx_pci_sdmmc"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    kernelPackages = pkgs.linuxPackages_latest;
    extraModulePackages = [ ];
      #options rtw89_8852bu ant_sel=2
    extraModprobeConfig = ''
      options rtw89_core disable_ps_mode=y
    '';

    resumeDevice = "/dev/nvme0n1p2";
    kernelParams = [
      "resume=/dev/nvme0n1p2"
      "resume_offset=126418944"
      "pcie_aspm=off"
    ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6a8d94fa-c931-45d0-9d22-ea7b6f8642c0";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/E80B-968E";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/mnt/windows" = {
    device = "/dev/disk/by-uuid/9EFC0CCBFC0CA01F";
    fsType = "ntfs";
    options = [
      "defaults"
      "nofail"
      "dmask=027"
      "fmask=027"
      "uid=1000"
      "gid=1000"
    ];
  };

  networking.useDHCP = lib.mkDefault true;

  swapDevices = [
    {
      device = "/swapfile";
      size = 20480;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    enableAllFirmware = true;
  };
}
